### ISSUE TITLE
TON ERROR:Connection lost

### ISSUE THREAD

**Issue by arvkonstantin** [EmelyanenkoK/tonwatcher#1]
Hello, I’m running the script at home, I am doing everything the same way

```
if __name__ == '__main__':
    loop.create_task(run_command(lite_client_path, "-C", lite_client_config_path, ))
    loop.create_task(get_account("EQAL7j_lEZn7DRvm29SdY5vWXD6l_en0OjalyeJYW8dzSpi4"))
    app = web.Application(loop=loop)
    web.run_app(app, port=server_port)
```

I did not change the run_command and get_account methods, but when I start, I see the following

```
# python3 run.py
run.py:105: DeprecationWarning: loop argument is deprecated
  app = web.Application(loop=loop)
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
2019-12-30 13:30:02,339 TON INFO:initialisation of ton client...
2019-12-30 13:30:02,343 TON INFO:Successfully initialised
2019-12-30 13:30:02,343 TON INFO:Processing getaccount request ['EQAL7j_lEZn7DRvm29SdY5vWXD6l_en0OjalyeJYW8dzSpi4']
b'getaccount EQAL7j_lEZn7DRvm29SdY5vWXD6l_en0OjalyeJYW8dzSpi4\n'
2019-12-30 13:30:02,344 TON ERROR:Connection lost
2019-12-30 13:30:02,344 asyncio ERROR:Task exception was never retrieved
future: <Task finished coro=<run_command() done, defined at run.py:26> exception=ConnectionResetError('Connection lost')>
Traceback (most recent call last):
  File "run.py", line 60, in run_command
    raise e
  File "run.py", line 53, in run_command
    await process.stdin.drain()
  File "/usr/lib/python3.7/asyncio/streams.py", line 348, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.7/asyncio/streams.py", line 202, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost
```

can you tell what could be the matter?

**Comment by EmelyanenkoK** [comment]
First of all, this repository is deprecated and method which we use here is quite bad: we just parsing stdout of the client to get result.
You should use https://github.com/viewst/pyTON

Regarding the error. Looks like something wrong with either your lite-client or config. Are you using the recent ones from test.ton.org? 
Try to run your command from the terminal 
`/root/liteclient-build/test-lite-client -C /root/liteclient-build/ton-lite-client-test1.config.json`
It will show you more information

**Comment by arvkonstantin** [comment]
The fact of the matter is that everything works well from the terminal

```
getaccount EQAL7j_lEZn7DRvm29SdY5vWXD6l_en0OjalyeJYW8dzSpi4
[ 3][t 2][1577706157.464133263][lite-client.cpp:999][!testnode] requesting account state for 0:0BEE3FE51199FB0D1BE6DBD49D639BD65C3EA5FDE9F43A36A5C9E2585BC7734A with respect to (-1,8000000000000000,1120091):0A852DD0EB45B436751B24DD4184840A7C47975D6D6885F3DDEB895E286C7FDE:DE1034FA1A8891A86E4BF8FBF97DFF59F3B68C2ADB3B412CE09D0F44FB87417D with savefile `` and mode -1
[ 3][t 1][1577706157.518396139][lite-client.cpp:1123][!testnode]        got account state for 0:0BEE3FE51199FB0D1BE6DBD49D639BD65C3EA5FDE9F43A36A5C9E2585BC7734A with respect to blocks (-1,8000000000000000,1120091):0A852DD0EB45B436751B24DD4184840A7C47975D6D6885F3DDEB895E286C7FDE:DE1034FA1A8891A86E4BF8FBF97DFF59F3B68C2ADB3B412CE09D0F44FB87417D and (0,2000000000000000,1475210):F240DFC731898EA61859241BF5AA9441D5D548C1451BB33FB817314883BA3817:C60D0589EE4277F8A2420E707583C9F7F9249C24A78FF06325D690C066D72EF0
account state is (account
  addr:(addr_std
    anycast:nothing workchain_id:0 address:x0BEE3FE51199FB0D1BE6DBD49D639BD65C3EA5FDE9F43A36A5C9E2585BC7734A)
  storage_stat:(storage_info
    used:(storage_used
      cells:(var_uint len:1 value:1)
      bits:(var_uint len:1 value:111)
      public_cells:(var_uint len:0 value:0)) last_paid:1577583803
    due_payment:nothing)
  storage:(account_storage last_trans_lt:1567634000002
    balance:(currencies
      grams:(nanograms
        amount:(var_uint len:5 value:90001978875))
      other:(extra_currencies
        dict:hme_empty))
    state:account_uninit))
x{C000BEE3FE51199FB0D1BE6DBD49D639BD65C3EA5FDE9F43A36A5C9E2585BC7734A2025BC2F04025D8000005B3F9122209453D224D7EC4_}
last transaction lt = 1567634000001 hash = 3E5F936959CC132807786D6E0438B0BB6AA888486037D19E7E4FC298B48B60AC
account balance is 90001978875ng
```
